In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, balanced_accuracy_score

In [57]:
data_file_path = "data/raw/dailog_acts.dat"

In [58]:
data = []
with open(data_file_path, "r") as f:
    for line in f:
        line = line.strip()

        if not line:
            continue
        
        act, utterance = line.split(maxsplit=1)
        #lowercasing
        data.append({"act": str.lower(act), "utterance": str.lower(utterance)})

In [59]:
df = pd.DataFrame(data=data)

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23998 entries, 0 to 23997
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   act        23998 non-null  str
 1   utterance  23998 non-null  str
dtypes: str(2)
memory usage: 375.1 KB

In [61]:
df.sample(15)

            act                                          utterance
8482   thankyou                                 thank you good bye
14455    inform                                             danish
6582    request                                            address
19054    inform                                        i dont care
4176    request                                        price range
3625     affirm  yes good afternoon im looking for a restaurant...
5003   thankyou                                 thank you good bye
4935     inform  im looking for a moderately price restaurant t...
18867   request                                       phone number
19938      null                                                sil
0        inform  im looking for a moderately priced restaurant ...
5103     inform            could i have a restaurant in the center
5450     inform  i am looking for a moderately priced restauran...
8153       null                                whats the other one
1060     inform                                   cheap restaurant

In [62]:
df["act"].unique()

<StringArray>
[  'inform',   'affirm',  'request', 'thankyou',     'null',      'bye',
  'reqalts',   'negate',  'confirm',    'hello',   'repeat',      'ack',
     'deny',  'restart',  'reqmore']
Length: 15, dtype: str

In [63]:
train_data, test_data = train_test_split(df,test_size=0.15,random_state=42)

In [65]:
with open("data/processed/test/fake_test_data.dat", "w", encoding="utf-8") as f:
    for _, row in test_data.iterrows():
        f.write(f"{row['act']} {row['utterance']}\n")

In [77]:
with open("data/processed/train/fake_train_data.dat", "w", encoding="utf-8") as f:
    for _, row in train_data.iterrows():
        f.write(f"{row['act']} {row['utterance']}\n")

In [66]:
test_data = []
with open("data/processed/test/fake_test_data.dat", "r") as f:
    for line in f:
        line = line.strip()

        if not line:
            continue
        
        act, utterance = line.split(maxsplit=1)
        #lowercasing
        test_data.append({"act": str.lower(act), "utterance": str.lower(utterance)})

In [67]:
test_df =  pd.DataFrame(data=test_data)

In [68]:
test_df.head()

        act                                          utterance
0  thankyou                            noise thank you goodbye
1   reqalts                                      anything else
2    inform                                      doesnt matter
3     hello                       hi im looking for cuban food
4    inform  i need an expensive restaurant serving british...

In [69]:
word_counts = {'inform' : {},   'affirm': {},  'request': {}, 'thankyou' : {},     'null': {},      'bye': {},
  'reqalts': {},   'negate': {},  'confirm': {},    'hello' : {},   'repeat': {},      'ack': {},
     'deny':{},  'restart':{},  'reqmore':{} }

for _,line in train_data.iterrows():
    act = line["act"]
    words = line["utterance"].split()
    for word in words:
        if word in word_counts[act]:
            word_counts[act][word] += 1
        else:
            word_counts[act][word] = 1

In [70]:
rules = {}

for act, counts in word_counts.items():
    rules[act] = sorted(
        counts,
        key=counts.get,
        reverse=True
)[0]

In [71]:
rules

{'inform': 'food',
 'affirm': 'yes',
 'request': 'the',
 'thankyou': 'thank',
 'null': 'noise',
 'bye': 'good',
 'reqalts': 'about',
 'negate': 'no',
 'confirm': 'it',
 'hello': 'hello',
 'repeat': 'repeat',
 'ack': 'okay',
 'deny': 'wrong',
 'restart': 'start',
 'reqmore': 'more'}

In [72]:
def classify(rules, test_data):
    df = test_data.copy()
    df["pred"] = None

    for index, row in df.iterrows():
        words = row["utterance"].split()
        print(words)

        for act, keyword in rules.items():
            if keyword in words:
                df.loc[index, "pred"] = act
                break
            else:
                df.loc[index, "pred"] = "null"

    return df

In [73]:
pred_df = classify(rules=rules,test_data=test_df)

['noise', 'thank', 'you', 'goodbye']
['anything', 'else']
['doesnt', 'matter']
['hi', 'im', 'looking', 'for', 'cuban', 'food']
['i', 'need', 'an', 'expensive', 'restaurant', 'serving', 'british', 'food']
['anything', 'else']
['thank', 'you', 'goodbye']
['and', 'the', 'post', 'code']
['what', 'is', 'the', 'address', 'phone', 'number', 'and', 'price', 'range']
['what', 'is', 'the', 'address']
['whats', 'the', 'phone', 'number']
['thank', 'you', 'good', 'bye']
['sil']
['what', 'is', 'the', 'post', 'code']
['thank', 'you', 'good', 'bye']
['sea', 'food']
['thank', 'you', 'good', 'bye']
['whats', 'the', 'address']
['restaurant']
['i', 'dont', 'care']
['thai', 'food']
['noise', 'address', 'and', 'the', 'post', 'code', 'of', 'the', 'venue']
['vietnamese']
['italian', 'food']
['im', 'looking', 'for']
['whats', 'the', 'phone', 'number']
['address']
['address']
['what', 'is', 'the', 'phone', 'number']
['what', 'is', 'the', 'phone', 'number']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['address']
['phone', 'number']
['no', 'how', 'about', 'vietnamese']
['tv_noise', 'im', 'looking', 'for', 'an', 'expensive', 'restaurant', 'and', 'it', 'should', 'serve', 'tuscan', 'food']
['thank', 'you', 'good', 'bye']
['west']
['i', 'want', 'a', 'moderate', 'priced', 'restaurant', 'in', 'the', 'south', 'of', 'town']
['i', 'am', 'looking', 'for', 'a', 'restaurant', 'serving', 'afghan', 'food']
['any']
['the', 'address']
['post', 'code']
['any', 'price', 'range']
['a', 'restaurant', 'serving', 'thai', 'food']
['thank', 'you', 'good', 'bye']
['i', 'dont', 'care']
['yeah']
['yes']
['address']
['any', 'type', 'of', 'food']
['any']
['phone', 'number', 'and', 'post', 'code']
['im', 'looking', 'for', 'a', 'restaurant']
['what', 'type', 'of', 'food', 'do', 'they', 'serve']
['moderately', 'priced', 'spanish', 'restaurant']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'goodbye']
['gastro', 'pub', 'food']
['cough']
['phone', 'number']
['it', 'doesnt', 'matter']
['thai', 'food']
['indian', 'food']
['thank', 'you', 'goodbye']
['unintelligible']
['no', 'thank', 'you', 'goodbye']
['whats', 'the', 'post', 'code']
['thank', 'you', 'good', 'bye']
['i', 'am', 'looking', 'for', 'a', 'moderately', 'priced', 'restaurant', 'in', 'the', 'north']
['uh', 'cheap', 'restaurant']
['okay', 'good', 'whats', 'the', 'address', 'for', 'that', 'one']
['sil']
['phone', 'number']
['thank', 'you', 'good', 'bye']
['and', 'the', 'phone', 'number']
['im', 'looking', 'for', 'an', 'expensive', 'restaurant', 'in', 'the', 'east', 'part', 'of', 'town']
['a', 'cheap', 'restaurant', 'in', 'the', 'north', 'part', 'of', 'town']
['im', 'looking', 'for', 'a', 'chinese', 'restaurant']
['i', 'dont', 'care']
['noise']
['doesnt', 'matter']
['yes', 'and', 'i', 'dont', 'care', 'about', 'the', 'price', 'range']
['how', 'about', 'italian']
['address']
['thank', 'you', 'good', 'bye']
['doesnt', 'matter']
['address']
['what', 'is', 'the', 'phone', 'number']
['yes']
['telephone', 'number']
['the', 'phone', 'number']
['anything', 'else']
['world', 'food']
['thank', 'you', 'good', 'bye']
['how', 'about', 'italian', 'food']
['im', 'looking', 'for', 'a', 'moderately', 'priced', 'restaurant', 'in', 'the', 'east', 'part', 'of', 'town']
['uh', 'a', 'restaurant', 'in', 'the', 'south', 'part', 'of', 'town']
['is', 'there', 'anything', 'else']
['i', 'dont', 'care']
['indian', 'food']
['where']
['an', 'expensive', 'restaurant', 'in', 'the', 'south', 'part', 'of', 'town']
['im', 'looking', 'for', 'an', 'expensive', 'restaurant', 'in', 'the', 'south', 'part', 'of']
['is', 'there', 'anything', 'else']
['thank', 'you', 'good', 'bye']
['and', 'whats', 'the', 'postal', 'code']
['noise']
['i', 'dont', 'care']
['what', 'about', 'italian', 'food']
['anything']
['cough']
['spanish']
['thank', 'you', 'good', 'bye']
['what', 'is', 'the', 'price', 'range']
['how', 'about', 'asian', 'food']
['noise']
['any']
['unintelligible']
['dont', 'care']
['address']
['what', 'about', 'korean']
['no']
['i', 'want', 'to', 'find', 'a', 'moderately', 'priced', 'restaurant', 'in', 'the', 'west', 'part', 'town']
['address']
['phone', 'number']
['phone', 'number']
['what', 'is', 'the', 'address']
['im', 'looking', 'for', 'an', 'expensive', 'restaurant', 'in', 'the', 'east', 'of', 'town']
['any']
['thank', 'you', 'good', 'bye']
['im', 'looking', 'for', 'a', 'moderately']
['okay', 'and', 'price', 'range']
['i', 'want', 'to', 'find', 'a', 'restaurant', 'that', 'serves', 'french', 'food']
['south', 'part', 'of', 'town']
['price', 'range']
['price', 'range']
['yes']
['phone', 'number']
['im', 'looking', 'for', 'a', 'moderately', 'priced', 'restaurant', 'that', 'serves', 'endonesian']
['okay']
['i', 'dont', 'care']
['thank', 'you', 'good', 'bye']
['i', 'dont', 'care']
['west']
['indian', 'food']
['whats', 'the', 'address']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['whats', 'its', 'post', 'code']
['i', 'want', 'to', 'find', 'a', 'moderately', 'priced', 'restaurant', 'that', 'serves', 'cuban', 'food']
['address']
['moderately', 'priced']
['what', 'is', 'the', 'signature', 'dish']
['north']
['moderately', 'priced']
['it', 'doesnt', 'matter']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['may', 'i', 'have', 'the', 'address', 'and', 'price', 'range']
['address']
['yes']
['north', 'part', 'of', 'town']
['anything', 'else']
['north']
['post', 'code']
['how', 'about', 'indian', 'food']
['center']
['may', 'i', 'have', 'the', 'address']
['and', 'post', 'code']
['caribbean', 'food']
['phone', 'number']
['how', 'about', 'indian', 'food']
['danish']
['expensive']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['east', 'part']
['moderate']
['no', 'any', 'area']
['uh', 'thank', 'you', 'good', 'bye']
['what', 'is', 'their', 'phone', 'number']
['spanish', 'food']
['does', 'it', 'serve', 'caribbean', 'food']
['seafood']
['it', 'doesnt', 'matter']
['breath', 'what', 'is', 'the', 'phone', 'number', 'and', 'post', 'code']
['expensive']
['thank', 'you', 'good', 'bye']
['i', 'dont', 'care']
['um', 'portuguese']
['moderately', 'priced']
['sil']
['looking', 'for', 'a', 'cheap', 'restaurant', 'that', 'serves', 'steak', 'house', 'food']
['type', 'of', 'food']
['hi', 'im', 'looking', 'for', 'a', 'restaurant', 'in', 'the']
['how', 'about', 'korean', 'food']
['address']
['italian']
['thank', 'you', 'good', 'bye']
['im', 'looking', 'for', 'a', 'restaurant', 'in', 'the', 'south', 'part', 'of', 'town', 'that', 'serves']
['yes']
['whats', 'the', 'address']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['phone', 'number']
['the', 'south', 'part', 'of', 'town']
['thank', 'you', 'good', 'bye']
['id', 'like', 'to', 'find', 'a', 'restaurant', 'in', 'any', 'area', 'serving', 'mediterranean', 'food']
['moderately', 'pri']
['how', 'about', 'a', 'turkish', 'restaurant']
['yes']
['north', 'american']
['cheap', 'restaurant']
['what', 'area', 'is', 'it', 'in']
['what', 'is', 'the', 'post', 'code']
['any']
['is', 'there', 'one', 'that', 'serves', 'indian', 'food']
['sil']
['how', 'about', 'modern', 'european']
['and', 'post', 'code']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['creative', 'food']
['dont', 'care']
['id', 'like', 'a', 'cantonese', 'resturant', 'in', 'the', 'south', 'part', 'of', 'town']
['thank', 'you', 'good', 'bye']
['adress']
['halal']
['the', 'phone', 'number']
['okay', 'just', 'regular', 'ecuadorean', 'food']
['south']
['cheap', 'cheap', 'restaurant']
['im', 'looking', 'for', 'moderately', 'priced', 'restaurant', 'that', 'serves']
['what', 'is', 'the', 'address']
['thank', 'you', 'good', 'bye']
['im', 'looking', 'for', 'am', 'expensive', 'restaurant', 'in', 'the', 'south', 'part']
['hi', 'im', 'looking', 'for', 'a', 'restaurant', 'that', 'servers']
['cheap']
['im', 'looking', 'for', 'a', 'restaurant', 'in', 'the', 'north', 'part', 'of', 'town', 'serving', 'french', 'type', 'of', 'food']
['yes']
['yes', 'i', 'am', 'in', 'the', 'east', 'part', 'of', 'town', 'right', 'now', 'and', 'i', 'am', 'looking', 'for', 'any', 'place', 'that', 'serves', 'indonesian', 'food']
['what', 'is', 'the', 'price', 'range']
['south']
['yes', 'im', 'looking', 'for', 'english', 'food']
['any']
['area']
['thai']
['thank', 'you', 'good', 'bye']
['phone', 'number']
['spanish', 'food']
['thank', 'you', 'good', 'bye']
['um', 'moderate']
['can', 'i', 'get', 'the', 'address', 'and', 'phone', 'number']
['expe']
['thank', 'you', 'good', 'bye']
['any']
['thank', 'you', 'good', 'bye']
['modern', 'european']
['whats', 'the', 'address', 'and', 'phone', 'number']
['west']
['is', 'there', 'anything', 'else']
['address']
['what', 'is', 'the', 'address']
['is', 'there', 'anything', 'else']
['expensive']
['what', 'is', 'the', 'phone', 'number']
['corsica', 'food']
['sil']
['phone', 'number']
['what', 'part', 'of', 'town']
['and', 'the', 'price', 'range']
['yes']
['i', 'want', 'a', 'singaporean', 'food', 'restaurant', 'in', 'the', 'center']
['phone', 'number']
['phone', 'number']
['what', 'is', 'the', 'area', 'of', 'the', 'venue']
['is', 'there', 'anything', 'else']
['and', 'the', 'phone', 'number']
['okay', 'thank', 'you', 'goodbye']
['im', 'looking', 'for', 'fusion', 'food']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['address']
['thank', 'you', 'good', 'bye']
['what', 'is', 'the', 'address']
['anything', 'else']
['noise']
['can', 'i', 'get', 'the', 'address']
['i', 'would', 'like', 'some', 'danish', 'food']
['address']
['sil']
['can', 'i', 'get', 'a', 'restaurant', 'with', 'vegetarian', 'food']
['it', 'doesnt', 'matter']
['whats', 'the', 'address']
['uh', 'can', 'i', 'get', 'the', 'post', 'code', 'and', 'phone', 'number']
['north', 'american', 'food']
['thank', 'you', 'good', 'bye']
['phone', 'number']
['okay', 'let', 'me', 'have', 'that', 'address']
['yes']
['south']
['im', 'looking', 'for', 'a', 'moderately', 'priced', 'resturant', 'in', 'the', 'east', 'part', 'of', 'town']
['what', 'is', 'the', 'address']
['noise']
['thank', 'you', 'good', 'bye']
['for', 'a', 'restaurant']
['thank', 'you', 'good', 'bye']
['north']
['south']
['mediterranean', 'food']
['dont', 'care']
['any']
['south', 'part', 'of', 'town']
['what', 'is', 'the', 'price', 'range']
['what', 'is', 'the', 'post', 'code']
['thank', 'you', 'good', 'bye']
['modern', 'european']
['what', 'is', 'the', 'address']
['can', 'i', 'have', 'an', 'expensive', 'restaurant']
['how', 'about', 'international', 'type', 'of', 'food']
['expensive']
['and', 'what', 'is', 'the', 'post', 'code']
['no']
['food']
['thank', 'you', 'goodbye']
['okay', 'thank', 'you']
['thank', 'you', 'good', 'bye']
['whats', 'the', 'address']
['phone', 'number']
['finished']
['vietnamese', 'food']
['what', 'asian', 'oriental', 'type', 'of', 'food']
['address']
['no', 'spanish', 'food']
['thank', 'you', 'good', 'bye']
['what', 'area', 'is', 'that']
['phone', 'number']
['moderate']
['tuscan', 'food']
['expensive']
['im', 'looking', 'for', 'a', 'cheap', 'restaurant', 'serving', 'mediterranean', 'food']
['no', 'im', 'looking', 'for', 'an', 'expensive', 'restaurant', 'in', 'the', 'east', 'part', 'of', 'town']
['thank', 'you', 'good', 'bye']
['cuban']
['could', 'i', 'have', 'the', 'address']
['dont', 'care']
['is', 'it', 'what', 'price', 'range']
['how', 'about', 'italian', 'food']
['okay', 'and', 'uh', 'whats', 'their', 'phone', 'number', 'please']
['thank', 'you', 'goodbye']
['um', 'im', 'looking', 'for', 'a', 'moderately', 'priced', 'restaurant', 'in', 'the', 'south', 'part', 'of', 'town']
['restaurant', 'in', 'south', 'part', 'of', 'town', 'serves']
['spanish', 'food']
['i', 'dont', 'care']
['phone', 'number']
['what', 'type', 'of', 'food', 'is', 'it']
['im', 'looking', 'for', 'a', 'restaurant', 'serving', 'venetian', 'food']
['thank', 'you', 'goodbye']
['restaurant']
['i', 'dont', 'care']
['sil']
['an', 'expensive', 'restaurant']
['anything', 'else']
['is', 'it', 'in', 'the', 'north', 'part', 'of', 'town']
['what', 'is', 'the', 'address']
['thank', 'you', 'good', 'bye']
['korean', 'food']
['phone', 'number']
['how', 'about', 'asian', 'oriental']
['thank', 'you', 'good', 'bye']
['how', 'bout', 'thai', 'food']
['thank', 'you', 'good', 'bye']
['what', 'is', 'the', 'address']
['yes', 'can', 'i', 'have', 'an', 'expensive', 'restaurant', 'in', 'the', 'east']
['i', 'need', 'a', 'restaurant', 'serving', 'turkish', 'food']
['what', 'type', 'of', 'venue']
['how', 'about', 'british', 'food']
['moderately', 'priced', 'afghan']
['address']
['are', 'there', 'any', 'turkish', 'restaurants']
['hello']
['im', 'looking', 'for', 'a', 'moderately', 'priced', 'restaurant', 'in', 'the', 'west', 'part']
['whats', 'the', 'address']
['what', 'is', 'the', 'address']
['phone', 'number']
['west']
['sorry']
['thank', 'you', 'good', 'bye']
['noise']
['address']
['whats', 'the', 'phone', 'number', 'for', 'that', 'place']
['how', 'about', 'chinese', 'food']
['cheap', 'restaurant', 'in', 'the', 'east', 'part', 'of', 'town']
['part', 'of', 'town', 'the', 'address', 'and', 'postal', 'code', 'please']
['right']
['im', 'looking', 'for', 'a', 'restaurant', 'in', 'the', 'east', 'part', 'of', 'town']
['address']
['a', 'restaurant', 'in', 'the', 'center', 'that', 'serves', 'leban']
['cheap']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['uh', 'dont', 'care']
['any']
['thank', 'you', 'good', 'bye']
['what', 'type', 'of', 'food', 'do', 'they', 'serve']
['thank', 'you', 'good', 'bye']
['moderately', 'priced', 'restaurant', 'in']
['south']
['dont', 'care']
['cheap']
['unintelligible']
['uh']
['cuban']
['i', 'dont', 'care']
['what', 'is', 'the', 'address']
['how', 'about', 'one', 'that', 'serves', 'asian', 'oriental', 'food']
['any', 'area']
['i', 'dont', 'care']
['no']
['im', 'looking', 'for', 'a', 'restaurant', 'in', 'the', 'west', 'part', 'of', 'town', 'and', 'it', 'sh']
['noise']
['yeah', 'i', 'need', 'um', 'um', 'm']
['what', 'is', 'the', 'address', 'and', 'phone', 'number']
['unintelligible']
['phone', 'number']
['uh', 'address']
['and', 'whats', 'the', 'phone', 'number']
['and', 'the', 'type', 'of', 'food']
['im', 'looking', 'for', 'a', 'greek', 'restaurant']
['thank', 'you', 'good', 'bye']
['it', 'doesnt', 'matter']
['what', 'type', 'of', 'food', 'does', 'it', 'serve']
['phone', 'number']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'goodbye']
['what', 'is', 'the', 'phone', 'number']
['noise']
['moderately']
['north']
['afghan']
['any', 'part']
['and', 'the', 'phone', 'number', 'okay']
['okay', 'how', 'about', 'the', 'address']
['system']
['middle']
['yes']
['anything', 'else']
['thank', 'you', 'good', 'bye']
['address']
['how', 'about', 'asian', 'oriental', 'type', 'of', 'food']
['i', 'want', 'to', 'find', 'an', 'expensive', 'restaurant', 'that', 'serves', 'vegetarian', 'food']
['food']
['the', 'phone', 'number']
['doesnt', 'matter']
['thank', 'you', 'good', 'bye']
['center', 'area']
['chinese']
['what', 'is', 'the', 'phone', 'number']
['im', 'looking', 'for', 'a', 'cheap', 'restaurant', 'serving', 'pan', 'as']
['yes']
['i', 'would', 'like', 'chinese', 'food']
['thank', 'you', 'good', 'bye']
['what', 'is', 'the', 'price', 'range']
['gastropub']
['phone', 'number']
['thank', 'you', 'goodbye']
['center', 'of', 'town']
['gastropub', 'food']
['may', 'i', 'have', 'the', 'address', 'and', 'phone', 'number']
['any', 'price', 'range']
['anything', 'else']
['i', 'need', 'a', 'restaurant', 'in', 'the', 'center', 'of', 'town']
['can', 'i', 'have', 'the', 'address', 'please']
['thank', 'you', 'good', 'bye']
['thai', 'restaurant']
['expensive', 'restaurant', 'serving', 'caribbean', 'food']
['how', 'about', 'spanish', 'food']
['i', 'dont', 'care']
['thank', 'you', 'good', 'bye']
['address']
['can', 'i', 'get', 'the', 'address']
['expensive']
['thank', 'you', 'good', 'bye']
['noise', 'can', 'i', 'get', 'the', 'address', 'and', 'phone', 'number']
['and', 'the', 'price', 'range']
['thank', 'you', 'good', 'bye']
['um', 'british']
['thank', 'you', 'good', 'bye']
['what', 'is', 'the', 'phone', 'number']
['hello']
['any']
['price', 'range']
['i', 'need', 'a', 'restaurant', 'that', 'serves', 'african', 'food']
['anything', 'else']
['can', 'i', 'get', 'the', 'phone', 'number']
['mexican']
['cheap']
['im', 'looking', 'for', 'portuguese', 'food']
['dont', 'care']
['i', 'dont', 'care']
['im', 'looking', 'for', 'an', 'expensive', 'restaurant', 'in', 'the', 'south', 'part', 'of', 'town']
['gastropub']
['yes']
['is', 'it', 'thai', 'food']
['french', 'food']
['food']
['spanish']
['breath', 'is', 'there', 'anything', 'else']
['thank', 'you', 'goodbye']
['im', 'looking', 'for', 'a', 'cheap', 'restaurant', 'and', 'it', 'should', 'be', 'in', 'the', 'south', 'part', 'of', 'town']
['south']
['phone', 'number']
['city', 'centre']
['i', 'dont', 'care']
['what', 'about', 'vietnamese', 'food']
['can', 'i', 'have', 'the', 'type', 'of', 'food']
['thank', 'you', 'good', 'bye']
['cheap', 'restaurant']
['how', 'about', 'vietnamese', 'food']
['thank', 'you', 'good', 'bye']
['noise']
['what', 'type', 'of', 'food', 'is', 'this']
['thank', 'you', 'good', 'bye']
['i', 'dont', 'care']
['thank', 'you', 'good', 'bye']
['and', 'the', 'phone', 'number']
['west']
['modern', 'european', 'food']
['system']
['noise']
['yeah']
['thank', 'you', 'good', 'bye']
['serving', 'cuban', 'food']
['uh', 'i', 'dont', 'mind']
['russian', 'food']
['phone', 'number']
['any']
['im', 'looking', 'for', 'a', 'restaurant', 'that', 'serves', 'gastropub', 'food']
['thank', 'you', 'goodbye']
['mediterranean', 'food']
['thank', 'you']
['how', 'about', 'vietnamese', 'food']
['im', 'looking', 'for', 'a', 'cheap', 'restaurant']
['find', 'restaurant', 'in', 'north', 'part', 'of', 'town', 'serving', 'asian', 'food']
['okay', 'what', 'is', 'the', 'addre']
['what', 'is', 'the', 'phone', 'number']
['sil']
['vietnamese']
['yes']
['what', 'is', 'the', 'address']
['i', 'dont', 'care']
['yes']
['ye']
['cheap', 'restaurant']
['noise']
['unintelligible']
['moderately', 'priced', 'restaurant']
['how', 'about', 'indian', 'food']
['im', 'looking', 'for', 'a', 'restaurant', 'in', 'the', 'north', 'part']
['is', 'there', 'anything', 'else']
['back']
['phone', 'number']
['im', 'looking', 'for', 'an', 'expensive', 'restaurant', 'that', 'serves', 'sea', 'food']
['thank', 'you', 'good', 'bye']
['okay', 'whats', 'the', 'address']
['asian', 'oriental', 'food']
['what', 'is', 'the', 'address']
['is', 'there', 'anything', 'else']
['any']
['anything', 'else']
['and', 'the', 'post', 'code']
['address']
['how', 'about', 'indian', 'food']
['not', 'sure']
['thank', 'you']
['phone', 'number']
['south']
['sil']
['no']
['whats', 'the', 'address']
['phone', 'number']
['thank', 'you', 'good', 'bye']
['what', 'is', 'the', 'phone', 'number']
['whats', 'the', 'phone', 'number']
['mediterranean']
['address']
['is', 'there', 'anything', 'else']
['i', 'dont', 'care']
['austrian', 'food']
['yes']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['noise']
['phone', 'number']
['malaysian']
['type', 'of', 'food']
['i', 'dont', 'care']
['noise']
['the', 'turkiesh']
['no', 'chinese']
['im', 'looking', 'for', 'a', 'cheap', 'restaurant']
['what', 'type', 'of', 'food', 'do', 'they', 'serve']
['thank', 'you', 'good', 'bye']
['any']
['sil']
['whats', 'the', 'phone', 'number']
['thank', 'you', 'goodbye']
['what', 'about', 'british', 'food']
['thank', 'you', 'good', 'bye']
['can', 'i', 'have', 'the', 'phone', 'number', 'and', 'the', 'price', 'range']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['i', 'dont', 'care']
['thank', 'you', 'good', 'bye']
['is', 'there', 'anything', 'else']
['unintelligible']
['im', 'looking', 'for', 'a', 'cheap', 'restaurant', 'in', 'the', 'east', 'part', 'of', 'town']
['okay', 'and', 'uh', 'the', 'phone', 'number']
['noise']
['what', 'is', 'the', 'address']
['thank', 'you', 'good', 'bye']
['thank', 'you', 'good', 'bye']
['do', 'you', 'have', 'modern', 'european', 'food']
['whats', 'the', 'phone', 'number']
['okay']
['anything', 'else']
['cuban']

In [74]:
pred_df.sample(15)

           act                                          utterance      pred
1014   request               what is the address and phone number   request
2830     hello                                              hello     hello
1688    inform                              serving jamaican food    inform
1246    inform                                              north      null
2001    inform                                i want chinese food    inform
3488       bye                                      k you goodbye      null
3089   reqalts                            how about in the center   request
484   thankyou                                 thank you good bye  thankyou
1261    affirm                                                yes    affirm
2845    inform            expensive restaurant south part of town      null
3565    inform                                        i dont care      null
1640    inform  something in the north part of town serving ch...    inform
337    request                                       phone number      null
3256      null                                              noise      null
2946   request                        may i have the phone number   request

In [75]:
def evaluate(df):
    y_true = df["act"]
    y_pred = df["pred"]
    accuracy = accuracy_score(y_true, y_pred)
    balanced_accuracy = balanced_accuracy_score(y_true, y_pred)
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Balanced Accuracy: {balanced_accuracy:.4f}")

In [76]:
evaluate(pred_df)

Accuracy: 0.5008
Balanced Accuracy: 0.4506